version: '3.8'

services:
  # Load balancer (nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    networks:
      - payment-processor
      - backend

  # FastAPI application instance 1
  app1:
    build: .
    expose:
      - "8000"
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 150M
    networks:
      - payment-processor
      - backend

  # FastAPI application instance 2  
  app2:
    build: .
    expose:
      - "8000"
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 150M
    networks:
      - payment-processor
      - backend

networks:
  payment-processor:
    external: true
  backend:
    driver: bridge