services:
  # Redis for Queue
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 40M
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # PostgreSQL for persistent data
  postgres:
    image: ghcr.io/pgmq/pg16-pgmq:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 80M
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 10s

  # API instances
  app1: &app
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/payments
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    networks:
      - backend

  app2:
    <<: *app

  # Load balancer (nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 60M
    networks:
      - backend

  # Payment Worker
  payment-worker1: &worker
    build:
      context: .
      dockerfile: ./payment-worker/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/payments
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 35M
    networks:
      - payment-processor
      - backend

  payment-worker2:
        <<: *worker

  # Health Checker
  health-checker:
    build:
      context: ./health-checker
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 30M
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f health-checker || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s


networks:
  payment-processor:
    external: true
  backend:
    driver: bridge

